### ISSUE TITLE
Rails7 + PostgreSQL で本番環境を再構築する

### ISSUE THREAD

**Issue by harutoreon** [harutoreon/docker_study#30]
## 概要
リポジトリ：surface-treatment-manager の Dockerfile に PostgreSQL を追加して、Render へのデプロイを成功させる。
下記の記事を参考にする。

[【Dockerfile全解説】Rails本番環境のための一番シンプルなDockerイメージを作る](https://qiita.com/notozeki/items/ac1bf72cf44b7ed6a6ad)

## todo
- [x] 本リポジトリに Dockerfile を追加する
- [x] 行単位で何をしているか把握する
- [x] ENTRYPOINT と CMD の違いを確認する
- [x] Multi-Stage Build を深掘りする
- [x] Dockerfile全解説
  - [x] 内容確認
  - [x] Dockerfile を Rails7 用に手直し
- [x] コンテナを起動して動作確認
- [x] コマンドを追加・削除する
- [x] ローカルで起動テスト
- [x] 完成した Dockerfile を surface-treatment-manager に戻す
- [x] Render へデプロイ
#### 追加タスク
- [x] Docker Build Kit について
- [x] ARG について
- [x] FROM について
- [x] WORKDIR について
- [x] RUN について
- [x] apt-get のアップデートとlibpq-devのインストールの順番は適当か
- [x] ENVについて
- [x] Multi-Stage Build について
- [x] libvips と pkg-config について
- [x] COPY について
- [x] Bootsnap について
- [x] precompile について
- [x] libsqlite3-0 と libvips について
- [x] --from=build について
- [x] USER について
- [x] ENTRYPOINT について
- [x] EXPOSE について
- [x] CMD について

**Comment by harutoreon** [comment]
Docker Build Kit の構文バージョンを指定
```dockerfile
# syntax = docker/dockerfile:1
```

**Comment by harutoreon** [comment]
ビルド時に使用される引数を定義。
```dockerfile
ARG RUBY_VERSION=3.2.0
```

**Comment by harutoreon** [comment]
Docker イメージのベースとなるイメージを指定。
エイリアスは base
```dockerfile
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim as base
```

**Comment by harutoreon** [comment]
作業ディレクトリを指定。
以降の命令で実行されるコンテキストは /rails となる。
```dockerfile
WORKDIR /rails
```

**Comment by harutoreon** [comment]
apt-get を使用してパッケージのアップデートと libpq-dev のインストールを実行。
-y オプションは、パッケージのインストールに関する質問に対して自動的に「yes」と回答するためのもの。
```dockerfile
RUN apt-get update && apt-get install -y libpq-dev
```

**Comment by harutoreon** [comment]
Docker イメージ内での環境変数の設定。
BUNDLE_DEPLOYMENT="1"で、プロジェクト内にGemをインストールする「デプロイメントモード」を有効にしている。
```dockerfile
ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development"
```

**Comment by harutoreon** [comment]
Docker のマルチステージビルドを使ってビルド用のステージを定義し、
そのステージに base というエイリアスを付けている。
```dockerfile
FROM base as build
```

**Comment by harutoreon** [comment]
Docker イメージ内でのパッケージの更新と追加。
- 推奨されるパッケージをインストールしない
- git、libvips、pkg-config のインストール
```dockerfile
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libvips pkg-config
```

**Comment by harutoreon** [comment]
Gemfile と Gemfile.lock を現在のディレクトリにコピー。
```dockerfile
COPY Gemfile Gemfile.lock ./
```

**Comment by harutoreon** [comment]
アプリケーションに必要な gem をインストール。
```dockerfile
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile
```

**Comment by harutoreon** [comment]
ビルドコンテキスト内の全てのファイルとディレクトリを、
イメージ内の現在の作業ディレクトリにコピー。
```dockerfile
COPY . .
```

**Comment by harutoreon** [comment]
Bootsnapを使用した app/ と lib/ の事前コンパイル
```dockerfile
RUN bundle exec bootsnap precompile app/ lib/
```

**Comment by harutoreon** [comment]
静的アセットの事前コンパイル
```dockerfile
RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
```

**Comment by harutoreon** [comment]
ベースイメージの再定義
```dockerfile
FROM base
```

**Comment by harutoreon** [comment]
SQLiteと画像処理ライブラリをインストール。
```dockerfile
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libsqlite3-0 libvips && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
```

**Comment by harutoreon** [comment]
マルチステージビルド機能を使って gem をコピー。
```dockerfile
COPY --from=build /usr/local/bundle /usr/local/bundle
```

**Comment by harutoreon** [comment]
マルチステージビルド機能を使ってアプリケーションをコピー。
```dockerfile
COPY --from=build /rails /rails
```

**Comment by harutoreon** [comment]
ディレクトリやファイルの所有者を設定。
```dockerfile
RUN useradd rails --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp
```

**Comment by harutoreon** [comment]
実行時に使用されるユーザーを指定。
```dockerfile
USER rails:rails
```

**Comment by harutoreon** [comment]
Docker コンテナが実行される際にデフォルトで実行されるファイルを指定。
```dockerfile
ENTRYPOINT ["/rails/bin/docker-entrypoint"]
```

**Comment by harutoreon** [comment]
Dockerコンテナの利用ポートを指定。
```dockerfile
EXPOSE 3000
```

**Comment by harutoreon** [comment]
ローカルサーバの起動。
```dockerfile
CMD ["./bin/rails", "server"]
```
